version: '3.9'

services:
  web:
    build:
      context: blog
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./blog:/app
    command: poetry run python manage.py runserver 0.0.0.0:8000